# This file is part of wampi.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

 
# The list of projects (home page)
# ----------------------------------------------------------------------

projects:
  path: /
  defaults: 
    _controller: 'Projects::projectsList'


# Page of a project
# ----------------------------------------------------------------------

project:
  path: /project/{path}
  defaults: 
    _controller: 'Project::project'
  requirements:
    _method: GET

project_process:
  path: /project/{path}
  defaults: 
    _controller: 'Project::process'
  requirements:
    _method: POST
    
    
# Information page
# ----------------------------------------------------------------------

information:
  path: /information
  defaults: 
    _controller: 'Information::infos'


# Configuration page
# ----------------------------------------------------------------------

configuration:
  path: /configuration
  defaults: 
    _controller: 'Configuration::form'
  requirements:
    _method: GET

configuration_process:
  path: /configuration
  defaults: 
    _controller: 'Configuration::process'
  requirements:
    _method: POST


# Installation page
# ----------------------------------------------------------------------

installation:
  path: /install
  defaults: 
    _controller: 'Installation::form'
  requirements:
    _method: GET

installation_process:
  path: /install
  defaults: 
    _controller: 'Installation::process'
  requirements:
    _method: POST


# Page to apply the update
# ----------------------------------------------------------------------

update:
  path: /update
  defaults: 
    _controller: 'Update::form'
  requirements:
    _method: GET

update_process:
  path: /update
  defaults: 
    _controller: 'Update::process'
  requirements:
    _method: POST


# Switch release type (stable or pre)
# ----------------------------------------------------------------------

update_switch_releases_type:
  path: /update/switch-releases-type
  defaults: 
    _controller: 'Update::switchReleasesType'


# Download an update archive
# ----------------------------------------------------------------------

update_download:
  path: /update/download
  defaults: 
    _controller: 'Update::download'


# Change language
# ----------------------------------------------------------------------

language:
    path: /language/{locale}
    defaults:
      _controller: 'BaseController::language'

 
# Emptying the cache
# ----------------------------------------------------------------------

clear_cache:
  path: /cc
  defaults: 
    _controller: 'BaseController::clearCache'


# Utility to remove a possible trailing slash
# ----------------------------------------------------------------------

remove_trailing_slash:
    path:     /{url}
    defaults:
      _controller: 'BaseController::removeTrailingSlash'
    requirements:
      url: .*/$
      _method: GET
