# This file is part of wampi.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

 
# La liste des projets
# ----------------------------------------------------------------------

projects:
  path: /
  defaults: 
    _controller: 'Projects::projectsList'


# La page d'un projet
# ----------------------------------------------------------------------

project:
  path: /project/{path}
  defaults: 
    _controller: 'Project::project'
  requirements:
    _method: GET

project_process:
  path: /project/{path}
  defaults: 
    _controller: 'Project::process'
  requirements:
    _method: POST
    
    
# La page d'informations
# ----------------------------------------------------------------------

information:
  path: /information
  defaults: 
    _controller: 'Information::infos'


# La page de configuration
# ----------------------------------------------------------------------

configuration:
  path: /configuration
  defaults: 
    _controller: 'Configuration::form'
  requirements:
    _method: GET

configuration_process:
  path: /configuration
  defaults: 
    _controller: 'Configuration::process'
  requirements:
    _method: POST


# La page d'installation
# ----------------------------------------------------------------------

installation:
  path: /install
  defaults: 
    _controller: 'Installation::form'
  requirements:
    _method: GET

installation_process:
  path: /install
  defaults: 
    _controller: 'Installation::process'
  requirements:
    _method: POST


# Changement de langue
# ----------------------------------------------------------------------

language:
    path: /language/{locale}
    defaults:
      _controller: 'BaseController::language'


# Utilitaire pour supprimer un éventuel slash de fin
# ----------------------------------------------------------------------

remove_trailing_slash:
    path:     /{url}
    defaults:
      _controller: 'BaseController::removeTrailingSlash'
    requirements:
      url: .*/$
      _method: GET
