
# La liste des projets
# ----------------------------------------------------------------------

projects:
  path: /
  defaults: 
    _controller: 'Projects::projectsList'


# La page d'un projet
# ----------------------------------------------------------------------

project:
  path: /project/{id}
  defaults: 
    _controller: 'Project::project'


# La page d'accueil du site
# ----------------------------------------------------------------------

configuration:
  path: /configuration
  defaults: 
    _controller: 'Configuration::form'
  requirements:
    _method: GET

configuration_process:
  path: /configuration
  defaults: 
    _controller: 'Configuration::process'
  requirements:
    _method: POST


# Utilitaire pour supprimer un éventuel slash de fin
# ----------------------------------------------------------------------

remove_trailing_slash:
    path:     /{url}
    defaults:
      _controller: 'BaseController::removeTrailingSlash'
    requirements:
      url: .*/$
      _method: GET
